# This file is auto-generated by MACH composer
# site: qa_site
terraform {
  backend "azurerm" {
    key                  = "qa/qa_site"
    storage_account_name = "blobptcomtoqa"
    container_name       = "tf-for-mach"
    resource_group_name  = "commercetools.pt-bdo-tp-qa-data"
  }
  required_providers {
    azurerm = {
      version = "~> 4.1.0"
    }
    commercetools = {
      source  = "labd/commercetools"
      version = "~> 1.15.1"
    }
  }
}

# File sources
# Resources
provider "azurerm" {
  subscription_id            = "12528073-4c59-453f-9f28-ab2c75e83118"
  skip_provider_registration = true
  features {
    resource_group {
      prevent_deletion_if_contains_resources = true
    }
    key_vault {
      purge_soft_deleted_keys_on_destroy = true
      recover_soft_deleted_keys          = true
    }
  }
}

locals {
  tags = {
    Environment = "qa"
    app         = "MACH"
  }
}

# Generated by mach-composer-plugin-commercetools
provider "commercetools" {
  client_id     = "q1kNU9NJdrb3AdZY2F6LtMnY"
  client_secret = "iShMrQqSnBVv0eKclIFXmLYfMVcGJYVY"
  project_key   = "dive-into-mach"
  scopes        = "manage_order_edits:dive-into-mach manage_customers:dive-into-mach"
  token_url     = "https://auth.europe-west1.gcp.commercetools.com"
  api_url       = "https://api.europe-west1.gcp.commercetools.com"
}

output "frontend_channels" {
  value = []
}

resource "commercetools_api_client" "frontend_credentials" {
  name = "frontend_credentials_terraform"
  scope = [
    "create_anonymous_token:dive-into-mach",
    "manage_my_profile:dive-into-mach",
    "manage_my_orders:dive-into-mach",
    "manage_my_shopping_lists:dive-into-mach",
    "manage_my_payments:dive-into-mach",
    "view_products:dive-into-mach",
    "view_project_settings:dive-into-mach",
  ]
}

output "frontend_client_scope" {
  value = commercetools_api_client.frontend_credentials.scope
}

output "frontend_client_id" {
  value = commercetools_api_client.frontend_credentials.id
}

output "frontend_client_secret" {
  value = commercetools_api_client.frontend_credentials.secret
}
