# This file is auto-generated by MACH composer
# site: ${ENVIRONMENT}_site
terraform {
  backend "azurerm" {
    key                  = "${ENVIRONMENT}/${ENVIRONMENT}_site"
    storage_account_name = "${AZURE_REMOTE_STATE_STORAGE_ACCOUNT}"
    container_name       = "${AZURE_REMOTE_STATE_CONTAINER_NAME}"
    resource_group_name  = "${AZURE_REMOTE_STATE_RESOURCE_GROUP}"
  }
  required_providers {
    azurerm = {
      version = "~> 4.1.0"
    }
    commercetools = {
      source  = "labd/commercetools"
      version = "~> 1.15.1"
    }
  }
}

# File sources
# Resources
provider "azurerm" {
  subscription_id            = "${AZURE_SUBSCRIPTION_ID}"
  skip_provider_registration = true
  features {
    resource_group {
      prevent_deletion_if_contains_resources = true
    }
    key_vault {
      purge_soft_deleted_keys_on_destroy = true
      recover_soft_deleted_keys          = true
    }
  }
}

locals {
  tags = {
    Environment = ENVIRONMENT
    app         = "MACH"
  }
}

# Generated by mach-composer-plugin-commercetools
provider "commercetools" {
  client_id     = SITE_COMMERCETOOLS_CLIENT_ID
  client_secret = SITE_COMMERCETOOLS_CLIENT_SECRET
  project_key   = SITE_COMMERCETOOLS_PROJECT_KEY
  scopes        = SITE_COMMERCETOOLS_SCOPES
  token_url     = "https://auth.europe-west1.gcp.commercetools.com"
  api_url       = "https://api.europe-west1.gcp.commercetools.com"
}

output "frontend_channels" {
  value = []
}

resource "commercetools_api_client" "frontend_credentials" {
  name = "frontend_credentials_terraform"
  scope = [
    "create_anonymous_token:${SITE_COMMERCETOOLS_PROJECT_KEY}",
    "manage_my_profile:${SITE_COMMERCETOOLS_PROJECT_KEY}",
    "manage_my_orders:${SITE_COMMERCETOOLS_PROJECT_KEY}",
    "manage_my_shopping_lists:${SITE_COMMERCETOOLS_PROJECT_KEY}",
    "manage_my_payments:${SITE_COMMERCETOOLS_PROJECT_KEY}",
    "view_products:${SITE_COMMERCETOOLS_PROJECT_KEY}",
    "view_project_settings:${SITE_COMMERCETOOLS_PROJECT_KEY}",
  ]
}

output "frontend_client_scope" {
  value = commercetools_api_client.frontend_credentials.scope
}

output "frontend_client_id" {
  value = commercetools_api_client.frontend_credentials.id
}

output "frontend_client_secret" {
  value = commercetools_api_client.frontend_credentials.secret
}
